<?php declare(strict_types=1); $path = $v->app->boards->postPath($post); ?>
<div role="article" class="post <?= $reply ? 'reply' : 'op' ?>" id="<?= $v::e($post['id']) ?>" data-post-id="<?= $v::e($post['id']) ?>">
<p class="intro"><label><input type="checkbox" class="select-post" aria-label="Select post <?= $v::e($post['id']) ?>" value="<?= $v::e($post['id']) ?>"> <span class="subject"><?= $v::e($post['subject']) ?></span> <span class="name"><?= $v::e($post['name']) ?></span></label> <time datetime="<?= gmdate('c', (int) $post['created']) ?>"><?= gmdate('m/d/y (D) H:i:s', (int) $post['created']) ?></time> <a class="post_no" href="<?= $v->url($path) ?>">No.</a><a class="post_no cite-post" data-cite="<?= $v::e($post['id']) ?>" href="<?= $v->url($path) ?>"><?= $v::e($post['id']) ?></a>
<?php if ((bool) $post['sticky']): ?> <span title="Sticky">📌</span><?php endif ?><?php if ((bool) $post['locked']): ?> <img src="<?= $v->url('static/locked.gif') ?>" alt="Locked"><?php endif ?>
<?php if (!$reply && $preview): ?> [<a href="<?= $v->url($path) ?>">Reply</a>]<?php endif ?> <span class="staff-controls" hidden>[<a href="<?= $v->url('mod.php?view=post&id=' . $post['id']) ?>">Manage</a>]</span></p>
<?php foreach ($files as $file): $mediaPath = 'media.php?id=' . $file['token']; ?><div class="file <?= count($files) > 1 ? 'multifile' : '' ?>"><p class="fileinfo">File: <a href="<?= $v->url($mediaPath) ?>" target="_blank" rel="noopener noreferrer"><?= $v::e($file['filename']) ?></a> <span class="unimportant">(<?= $v::e(round((int) $file['bytes'] / 1024, 1)) ?> KB<?= $file['width'] ? ', ' . $v::e($file['width']) . '×' . $v::e($file['height']) : '' ?>)</span></p>
<?php if ($file['mime'] === 'video/mp4'): ?><video class="post-video" controls preload="metadata" playsinline src="<?= $v->url($mediaPath) ?>" poster="<?= $v->url('static/video.png') ?>">Your browser cannot play this MP4. <a href="<?= $v->url($mediaPath) ?>">Download video</a>.</video>
<?php else: ?><a class="image-expand" href="<?= $v->url($mediaPath) ?>"><img class="post-image" loading="lazy" src="<?= $v->url($mediaPath . '&thumb=1') ?>" data-original="<?= $v->url($mediaPath) ?>" alt="<?= $v::e($file['filename']) ?>" width="<?= max(1, (int) round((int) $file['width'] * min(1, 250 / max(1, (int) $file['width']), 250 / max(1, (int) $file['height'])))) ?>"></a><?php endif ?></div><?php endforeach ?>
<div class="body"><?= $v->formatter->render($preview && mb_strlen($post['body']) > 3000 ? mb_substr($post['body'], 0, 3000) . '…' : $post['body'], $post['slug']) ?><?php if ($preview && mb_strlen($post['body']) > 3000): ?><p><a href="<?= $v->url($path) ?>">Read the full post</a></p><?php endif ?></div>
<?php if ($post['edited'] !== null): ?><p class="unimportant">Edited <?= gmdate('Y-m-d H:i', (int) $post['edited']) ?> UTC</p><?php endif ?>
<div class="clear"></div></div><?php if ($reply): ?><br class="reply-break"><?php endif ?>
